# Generated by Django 4.2 on 2025-09-04 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(blank=True, max_length=32, null=True)),
                ('time_ms', models.IntegerField(blank=True, null=True)),
                ('moves', models.TextField(blank=True, default='[]')),
                ('length_htm', models.IntegerField(default=0)),
                ('length_qtm', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
