# Generated by Django 4.2 on 2025-09-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubikapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solve',
            name='state_54',
            field=models.CharField(blank=True, max_length=54, null=True),
        ),
        migrations.AlterField(
            model_name='solve',
            name='length_htm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solve',
            name='length_qtm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solve',
            name='method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='solve',
            name='moves',
            field=models.TextField(blank=True, null=True),
        ),
    ]
